name: Swift

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer

jobs:
  swift-macos:
    name: Swift (macOS)
    runs-on: macos-26
    timeout-minutes: 30
    steps:
    - name: Checkout source
      uses: actions/checkout@v6
    - name: Swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v

  swift-linux:
    name: Swift (Linux)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout source
      uses: actions/checkout@v6
    - name: Swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
